Адаптивная сетка для главной страницы
htmlacademy-adaptive/960263-cat-energy-22 pull request #8
Opened 2021-04-23 18:41 UTC by AMenyakin

2021-04-25 17:16 UTC, ElseeCCD requested changes

2021-04-25 17:16 UTC, ElseeCCD commented on source/index.html
> +      <div class="main-page-header__right-column">
Почему так продублировал код? И навигацию и контент "Функциональное питание для котов"? Не должно дублироваться, всё должно быть хедером. На десктопах навигацию можно, например, абсолютно спозиционировать, а зеленый фон тянуть по правому краю до конца экрана.

2021-04-25 17:16 UTC, ElseeCCD commented on source/sass/blocks/example.scss
> +    background-color: $gallery;
комментарии не забывай удалять

2021-04-25 17:16 UTC, ElseeCCD commented on source/sass/blocks/page-header.scss
> +  @media (max-width: $mobile-width-only) {
Почему не $tablet-width? )

2021-04-25 17:16 UTC, ElseeCCD commented on source/sass/blocks/programs.scss
> +  @media (min-width: $tablet-width) and (max-width: $tablet-width-only) {
почему не $desktop-width? )

2021-04-25 17:16 UTC, ElseeCCD commented on source/sass/common.scss
> +$tablet-width-only: 1339px;
$mobile-width-only и $tablet-width-only довольно сомнительные брейкпоинты )

2021-04-26 14:01 UTC, AMenyakin commented on source/sass/blocks/page-header.scss
> +  @media (max-width: $mobile-width-only) {
Потому что навигация изначально скрыта только для ширины до 767px включительно. Для бОльшей ширины она отображается всегда.

2021-04-26 14:04 UTC, AMenyakin commented on source/sass/blocks/programs.scss
> +  @media (min-width: $tablet-width) and (max-width: $tablet-width-only) {
Потому что display: flex тут нужен только на ширине от 768px до 1439 включительно.

2021-04-26 14:07 UTC, AMenyakin commented on source/sass/common.scss
> +$tablet-width-only: 1339px;
Почему? $mobile-width-only нужен, когда правило необходимо применять только для ширины до 767px включительно, а  $tablet-width-only, от 768 до 1439 включительно. Единственное - я тут ошибся, не 1339, а 1439px.

2021-04-26 14:08 UTC, AMenyakin commented on source/index.html
>          <div class="page-header__wrapper">
Похоже, что да

2021-04-27 06:44 UTC, ElseeCCD approved these changes

2021-04-27 06:44 UTC, ElseeCCD commented on source/sass/blocks/main-nav.scss
> +  &:not(:last-child) {
тут можно было обойтись без not, а, например, при помощи & + &

2021-04-27 06:44 UTC, ElseeCCD commented on source/sass/blocks/main-page.scss
> +    position: absolute;
z-index еще нужно добавить, меню сейчас перекрыто нижними блоками

2021-04-27 06:44 UTC, merged